name: PR
on:
  pull_request:

jobs:
  Run-CI-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Run Tox tests
        run: scripts/ci.sh
      - name: Run Keycloak config tests
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "up --build --exit-code-from keycloak_config"
